services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
  web:
    image: piligrim-web:${TAG-latest}
    restart: unless-stopped
  api:
    image: piligrim-api:${TAG-latest}
    restart: unless-stopped
volumes:
  caddy_data: {}
  caddy_config: {}
